jobs:
  run:
    name: Main
    runs-on: ubuntu-20.04

    steps:
      - name: Start
        uses: actions/checkout@v2
      - name: Fetch Packages
        run: sudo apt-get update && sudo apt-get install -y libhwloc15 unrar
      - name: Check
        run: ./ci/action

name: Verify

on:
  schedule:
    - cron: "50 */6 * * *"
